quotes:
  - { code: "USD", symbol: "$", name: "US Dollar", flag: "ðŸ‡ºðŸ‡¸" }
  - { code: "EUR", symbol: "â‚¬", name: "Euro", flag: "ðŸ‡ªðŸ‡º" }
  - { code: "MYR", symbol: "RM", name: "Malaysian Ringgit", flag: "ðŸ‡²ðŸ‡¾" }

exchanges:
  - provider: "dev-mock"
    base: "BTC"
    quote: "*"
    enabled: true
    config:
      devMockPrice:
        BTC:
          EUR: 17500
          USD: 20000
          MYR: 78000
    # Following require dummy values
    name: ""
    cron: "*/5 * * * * *"
