name: "E2e test"

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: execute via bats
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          df -h /

      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Run bats tests
        env:
          DOCKER_API_VERSION: "1.44"
        run: |
          nix develop -c ./bats/ci_run.sh

      - name: Rename Tilt log
        if: always()
        run: mv bats/.e2e-tilt.log bats/e2e-tilt.log

      - name: Upload Tilt log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Tilt log
          path: bats/e2e-tilt.log
